-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 10:37:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb3 ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(255) NOT NULL,
  `numero` INT NULL DEFAULT NULL,
  `piso` INT NULL DEFAULT NULL,
  `puerta` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `direccion_id` INT NOT NULL,
  `telefono` INT NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `clienteRecomendador` INT NULL DEFAULT NULL,
  `empleadoQueAtiende` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  INDEX `direccion_id_idx` (`direccion_id` ASC) VISIBLE,
  CONSTRAINT `direccion_id`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `Optica`.`direccion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `direccion_id1` INT NOT NULL,
  `telefono` INT NOT NULL,
  `fax` INT NULL DEFAULT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `direccion_id_idx` (`direccion_id1` ASC) VISIBLE,
  CONSTRAINT `direccion_id1`
    FOREIGN KEY (`direccion_id1`)
    REFERENCES `Optica`.`direccion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `proveedor_id_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Optica`.`proveedor` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`gafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`gafa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_id` INT NOT NULL,
  `graduacion` INT NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `colorCristal` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `marca_id_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `marca_id`
    FOREIGN KEY (`marca_id`)
    REFERENCES `Optica`.`marca` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `Optica`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gafa_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `empleado_que_atendio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `empleado_que_atendio_idx` (`empleado_que_atendio` ASC) VISIBLE,
  INDEX `gafa_id_idx` (`gafa_id` ASC) VISIBLE,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`id`)
    REFERENCES `Optica`.`cliente` (`id`),
  CONSTRAINT `empleado_que_atendio`
    FOREIGN KEY (`empleado_que_atendio`)
    REFERENCES `Optica`.`empleado` (`id`),
  CONSTRAINT `gafa_id`
    FOREIGN KEY (`gafa_id`)
    REFERENCES `Optica`.`gafa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;

USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tipo_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoriaPizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoriaPizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_tipo_pizza` INT NULL DEFAULT NULL,
  `categoriaPizzacol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_tipo_pizza_idx` (`id_tipo_pizza` ASC) VISIBLE,
  CONSTRAINT `id_tipo_pizza`
    FOREIGN KEY (`id_tipo_pizza`)
    REFERENCES `pizzeria`.`tipo_producto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provincia_id` INT NOT NULL,
  `localidadNom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `localidadNom_UNIQUE` (`localidadNom` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `provincia_id`
    FOREIGN KEY (`id`)
    REFERENCES `pizzeria`.`provincia` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `codigo postal` INT NOT NULL,
  `localidad_id` INT NOT NULL,
  `provincia_id1` INT NOT NULL,
  `numTelefono` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `numTelefono_UNIQUE` (`numTelefono` ASC) VISIBLE,
  INDEX `provincia_id_idx` (`provincia_id1` ASC) VISIBLE,
  INDEX `localidad_id_idx` (`localidad_id` ASC) VISIBLE,
  CONSTRAINT `localidad_id`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `pizzeria`.`localidad` (`id`),
  CONSTRAINT `provincia_id1`
    FOREIGN KEY (`provincia_id1`)
    REFERENCES `pizzeria`.`provincia` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`tienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `codigo postal` VARCHAR(45) NULL DEFAULT NULL,
  `localidad_id1` INT NOT NULL,
  `provincia_id2` INT NOT NULL,
  `num_comandas` INT NULL DEFAULT NULL,
  `num_empleados` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `localidad_idx` (`localidad_id1` ASC) VISIBLE,
  CONSTRAINT `localidad_id1`
    FOREIGN KEY (`localidad_id1`)
    REFERENCES `pizzeria`.`localidad` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `domicilioS/N` TINYINT NOT NULL,
  `cantidadPorProducto` INT NOT NULL,
  `precioTotal` FLOAT NOT NULL,
  `user_id` INT NOT NULL,
  `num_productos` INT NOT NULL,
  `tienda_id` INT NULL DEFAULT NULL COMMENT 'Para indicar la tienda que realiza el pedido',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `tienda_id_idx` (`tienda_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tienda_id`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzeria`.`tienda` (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pizzeria`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`repartidor_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`repartidor_comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `id_repartidor` TINYINT NOT NULL,
  PRIMARY KEY (`id_repartidor`),
  INDEX `fk_empleado_has_comanda_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_has_comanda_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `id_tienda` INT NOT NULL COMMENT 'Para indicar la tienda en la que trabaja',
  `es_repartidor` TINYINT NULL DEFAULT NULL,
  `comanda_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tienda_idx` (`id_tienda` ASC) VISIBLE,
  INDEX `es_repartidor_idx` (`es_repartidor` ASC) VISIBLE,
  CONSTRAINT `es_repartidor`
    FOREIGN KEY (`es_repartidor`)
    REFERENCES `pizzeria`.`repartidor_comanda` (`id_repartidor`),
  CONSTRAINT `id_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria`.`tienda` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `precio` FLOAT NOT NULL,
  `created_by` INT NOT NULL,
  `categoria_Pizza` INT NULL DEFAULT NULL,
  `id_tienda_que_gestiona` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_id_idx` (`tipo_id` ASC) VISIBLE,
  INDEX `categoria_Pizza_idx` (`categoria_Pizza` ASC) VISIBLE,
  INDEX `id_tienda_que_gestiona_idx` (`id_tienda_que_gestiona` ASC) VISIBLE,
  CONSTRAINT `categoria_Pizza`
    FOREIGN KEY (`categoria_Pizza`)
    REFERENCES `pizzeria`.`categoriaPizza` (`id`),
  CONSTRAINT `id_tienda_que_gestiona`
    FOREIGN KEY (`id_tienda_que_gestiona`)
    REFERENCES `pizzeria`.`tienda` (`id`),
  CONSTRAINT `tipo_id`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `pizzeria`.`tipo_producto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`order_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comanda_id` INT NOT NULL,
  `producto_category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `comanda_id`, `producto_category_id`),
  INDEX `fk_comanda_has_producto_producto1_idx` (`producto_category_id` ASC) VISIBLE,
  INDEX `fk_comanda_has_producto_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_has_producto_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`id`),
  CONSTRAINT `fk_comanda_has_producto_producto1`
    FOREIGN KEY (`producto_category_id`)
    REFERENCES `pizzeria`.`producto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------------------------------------------------
-- PRUEBAS PARA COMPROBAR QUE FUNCIONA>

INSERT INTO provincia (name) values 
('Albacete'),
('Cuenca'),
('Lazio'),
('Lleida');

INSERT INTO localidad (provincia_id, localidadNom) values 
(1,'Pego'),
(2,'Alcala'),
(3,'Casalbertone'),
(4,'Osona');

INSERT INTO tipo_producto (name) values ('PIAZZAS'),('HAMBURGUESAS'),('BEBIDAS');

INSERT INTO tienda (nombre, direccion, `codigo postal`, localidad_id1, provincia_id2) 
values 
('pizas pizzas','c/anares 23',' 09092',1,1),
('gioconda','c/palatros 222',' 04442',2,2),
('antonio pizzas','c/mateo 43',' 0456562',3,3),
('aha','c/pizzas 3',' 09595',4,4);

INSERT INTO	 categoriaPizza (name, id_tipo_pizza, categoriaPizzacol) 
values
('Pizza con piña',1,'vegana'),
('bbq',1,'spicy');

INSERT INTO cliente (nombre, apellido, direccion, `codigo postal`,localidad_id,provincia_id1,numTelefono) values
('Luis','Rodriguez','c/rodriguez',09990,2,2,7876763),
('Marc','perez','c/marc',33399,3,3,72222263),
('Helena','castro','c/helena',09990,1,1,7000063);

INSERT INTO producto (tipo_id,nombre,descripcion,precio,created_by,categoria_Pizza,id_tienda_que_gestiona) values
(3,'pi;a','esto es una descripcion',3.44,1,1,1);

INSERT INTO comanda (`domicilioS/N`,cantidadPorProducto,precioTotal,user_id,num_productos,tienda_id)
values
(0,1,7.99,1,1,1);
INSERT INTO order_detail  (comanda_id, producto_category_id)values(1,1);

INSERT INTO repartidor_comanda values
(1,1);

INSERT INTO empleado (name, nif, telefono, id_tienda, es_repartidor,comanda_id ) values
('manolo', '222222222r',666888222,1,1,1);
INSERT INTO empleado (name, nif, telefono, id_tienda, es_repartidor) values
('luis','111111e',66622655,2,1);
-- LOS COCINEROS NO TIENEN LA COLUMNA es_repartidor
INSERT INTO empleado (name, nif, telefono, id_tienda) values
('Felipe', '000000000w',666000000,1),
('MArta','5555555555r',666000000,2);

-- para ver los produtcos tipos bebidas
SELECT p.id, p.tipo_id, t.id from producto p left join tipo_producto t on p.tipo_id = 3;
-- para ver las bebidas vendidas:
SELECT o.comanda_id , o.producto_category_id, p.tipo_id from order_detail o left join producto p on p.tipo_id =o.producto_category_id;
-- listar comandas efectuadas por un empleado:
-- para ver que empleados son repartidores seleccionamos primero los que tienen  es_repartidor =1:
SELECT * from empleado where es_repartidor =1;
-- y los empleados que han hecho comandas tienen una comanda_id y son repartidores,
-- entonces, para ver las comandas efectuado por un empleado buscamos la id_repartidor 
-- en concreto que tenga comanda:

SELECT * from empleado where  comanda_id >0;
-- y además vemos que si tiene comanda es repartidor
