-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 20:41:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(16) NOT NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` INT NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `clienteRecomendador` VARCHAR(45) NULL,
  `empleadoQueAtiende` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(254) NULL,
  `telefono` INT NOT NULL,
  `fax` INT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`gafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gafa` (
  `id` INT NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `graduacion` INT NULL,
  `montura` VARCHAR(45) NULL,
  `colorCristal` VARCHAR(45) NULL,
  `precio` FLOAT NOT NULL,
  `proveedorNif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `proveedorNif_idx` (`proveedorNif` ASC) VISIBLE,
  CONSTRAINT `proveedorNif`
    FOREIGN KEY (`proveedorNif`)
    REFERENCES `mydb`.`proveedor` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
 
 -- para hacer la id que incremente:
ALTER TABLE cliente MODIFY COLUMN id int auto_increment;
ALTER TABLE gafa MODIFY COLUMN id int auto_increment;
ALTER TABLE proveedor MODIFY COLUMN id int auto_increment;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
